let ctx,clients=[],operations=[],shifts=[],profiles=[],links=[],leaderLinks=[],requests=[]
const options=(items,label,fn)=>`<option value="">${label}</option>`+items.map(x=>`<option value="${x.id}">${escapeHTML(fn(x))}</option>`).join('')
async function loadAll(){
  const results=await Promise.all([
    db.from('clients').select('*').order('name'),db.from('operations').select('*,clients(name)').order('department'),db.from('shifts').select('*').order('name'),db.from('profiles').select('*').order('full_name'),db.from('onsite_operations').select('*'),db.from('leader_operations').select('*'),db.from('disciplinary_requests').select('*,operations(cost_center,department)').order('created_at',{ascending:false}),db.from('request_audit_log').select('*').order('created_at',{ascending:false}).limit(100)
  ])
  const names=['clientes','operações','turnos','usuários','vínculos Onsite','vínculos Líder','solicitações','auditoria']
  const failures=results.map((result,index)=>result.error?`${names[index]}: ${result.error.message}`:null).filter(Boolean)
  if(failures.length) alert('Alguns dados não puderam ser carregados:\n\n'+failures.join('\n'))
  ;[clients,operations,shifts,profiles,links,leaderLinks,requests]=results.slice(0,7).map(r=>r.data||[])
  renderSelects();renderUsers();renderOperations();renderRequests();renderAudit(results[7].data||[]);renderStats();if(typeof loadManagement==='function')loadManagement();if(typeof prepareDashboard==='function')prepareDashboard();if(typeof loadWorkforce==='function')loadWorkforce()
}
function renderStats(){statUsers.textContent=profiles.filter(x=>x.active).length;statPending.textContent=requests.filter(x=>!x.applied_date&&!['cancelado','concluido'].includes(x.status)).length;statOperations.textContent=operations.filter(x=>x.active).length}
function operationLabel(x){return `${x.clients?.name||''} | ${x.cost_center} | ${x.department}`}
function onsiteOperationOptions(onsiteId=null){const allowed=operations.filter(operation=>operation.active&&!links.some(link=>link.operation_id===operation.id&&link.onsite_id!==onsiteId));return allowed.map(operation=>`<option value="${operation.id}">${escapeHTML(operationLabel(operation))}</option>`).join('')}
function renderSelects(){operationClient.innerHTML=options(clients.filter(x=>x.active),'Selecione o cliente',x=>x.name);leaderOperation.innerHTML=operations.filter(x=>x.active).map(x=>`<option value="${x.id}">${escapeHTML(operationLabel(x))}</option>`).join('');onsiteOperations.innerHTML=onsiteOperationOptions();leaderShift.innerHTML=options(shifts.filter(x=>x.active),'Selecione o turno',x=>x.name)}
function renderUsers(){const q=userSearch.value.toLowerCase(),role=userRoleFilter.value;const rows=profiles.filter(p=>(!role||p.role===role)&&(`${p.full_name} ${p.email}`.toLowerCase().includes(q))).map(p=>{const shift=shifts.find(s=>s.id===p.shift_id),detail=p.role==='leader'?`${leaderLinks.filter(x=>x.leader_id===p.id).length} operação(ões) / ${shift?.name||'—'}`:p.role==='onsite'?`${links.filter(x=>x.onsite_id===p.id).length} operação(ões)`:'—';return `<tr><td><strong>${escapeHTML(p.full_name)}</strong></td><td>${roleLabel(p.role)}</td><td>${escapeHTML(p.email)}</td><td>${escapeHTML(detail)}</td><td><span class="badge ${p.active?'badge-green':'badge-gray'}">${p.active?'Ativo':'Inativo'}</span></td><td><div class="actions"><button class="btn btn-light" onclick="openEditUser('${p.id}')">Editar</button><button class="btn btn-light" onclick="toggleUser('${p.id}',${!p.active})">${p.active?'Desativar':'Reativar'}</button><button class="btn btn-light" onclick="resetPassword('${p.id}')">Nova senha</button></div></td></tr>`}).join('');userRows.innerHTML=rows||'<tr><td colspan="6" class="empty">Nenhum usuário encontrado.</td></tr>'}
function renderOperations(){operationRows.innerHTML=operations.map(o=>`<tr><td>${escapeHTML(o.clients?.name)}</td><td>${escapeHTML(o.cost_center)}</td><td>${escapeHTML(o.department)}</td><td>${escapeHTML(o.city_state||'—')}</td><td><span class="badge ${o.active?'badge-green':'badge-gray'}">${o.active?'Ativa':'Inativa'}</span></td><td><button class="btn btn-light" onclick="editOperation('${o.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma operação cadastrada.</td></tr>'}
function renderRequests(){assignmentRows.innerHTML=requests.map(r=>{const onsite=profiles.find(p=>p.id===r.assigned_onsite_id);return `<tr><td>${escapeHTML(r.employee_name)}</td><td>${escapeHTML(r.operations?.cost_center)}<br><small>${escapeHTML(r.operations?.department)}</small></td><td>${escapeHTML(r.penalty_type)}</td><td><span class="badge ${r.assigned_onsite_id?'badge-blue':'badge-yellow'}">${escapeHTML(r.status)}</span></td><td>${escapeHTML(onsite?.full_name||'Não atribuído')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">Nenhuma solicitação.</td></tr>'}
function renderAudit(items){auditRows.innerHTML=items.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('pt-BR')}</td><td>${escapeHTML(profiles.find(p=>p.id===a.actor_id)?.full_name||'Sistema')}</td><td>${escapeHTML(a.action)}</td><td>${escapeHTML(a.old_status||'—')}</td><td>${escapeHTML(a.new_status||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum registro.</td></tr>'}
userRole.addEventListener('change',()=>{const r=userRole.value;leaderOperationField.classList.toggle('hidden',r!=='leader');leaderShiftField.classList.toggle('hidden',r!=='leader');onsiteOperationsField.classList.toggle('hidden',r!=='onsite');leaderOperation.required=r==='leader';leaderShift.required=r==='leader';onsiteOperations.required=r==='onsite'})
editUserRole.addEventListener('change',toggleEditFields)
function toggleEditFields(){const r=editUserRole.value;editLeaderOperationField.classList.toggle('hidden',r!=='leader');editLeaderShiftField.classList.toggle('hidden',r!=='leader');editOnsiteOperationsField.classList.toggle('hidden',r!=='onsite');editLeaderOperation.required=r==='leader';editLeaderShift.required=r==='leader'}
function openEditUser(id){const p=profiles.find(item=>item.id===id);if(!p)return;editUserId.value=p.id;editUserName.value=p.full_name||'';editUserEmail.value=p.email||'';editUserPhone.value=p.phone||'';editUserRole.value=p.role;editLeaderOperation.innerHTML=leaderOperation.innerHTML;editLeaderShift.innerHTML=leaderShift.innerHTML;editOnsiteOperations.innerHTML=onsiteOperationOptions(p.id);editLeaderShift.value=p.shift_id||'';const selectedLeaderOps=leaderLinks.filter(link=>link.leader_id===p.id).map(link=>link.operation_id);[...editLeaderOperation.options].forEach(option=>option.selected=selectedLeaderOps.includes(option.value));const selectedOnsiteOps=links.filter(link=>link.onsite_id===p.id).map(link=>link.operation_id);[...editOnsiteOperations.options].forEach(option=>option.selected=selectedOnsiteOps.includes(option.value));toggleEditFields();editUserCard.classList.remove('hidden');editUserCard.scrollIntoView({behavior:'smooth'})}
function closeEditUser(){editUserCard.classList.add('hidden');editUserForm.reset()}
userSearch.addEventListener('input',renderUsers);userRoleFilter.addEventListener('change',renderUsers)
clientForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('clients').insert({name:clientName.value.trim()});if(error)return alert(error.message);e.target.reset();loadAll()})
shiftForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('shifts').insert({name:shiftName.value.trim()});if(error)return alert(error.message);e.target.reset();loadAll()})
function editOperation(id){const operation=operations.find(item=>item.id===id);if(!operation)return;operationEditId.value=operation.id;operationClient.value=operation.client_id;costCenter.value=operation.cost_center||'';department.value=operation.department||'';operationCity.value=operation.city_state||'';operationFormTitle.textContent='Editar operação';operationSaveBtn.textContent='Salvar alterações';operationCancelBtn.classList.remove('hidden');operationForm.scrollIntoView({behavior:'smooth'})}
function cancelEditOperation(){operationForm.reset();operationEditId.value='';operationFormTitle.textContent='Nova operação';operationSaveBtn.textContent='Cadastrar';operationCancelBtn.classList.add('hidden')}
operationForm.addEventListener('submit',async e=>{e.preventDefault();const payload={client_id:operationClient.value,cost_center:costCenter.value.trim().toUpperCase(),department:department.value.trim(),city_state:operationCity.value.trim()};const query=operationEditId.value?db.from('operations').update(payload).eq('id',operationEditId.value):db.from('operations').insert(payload);const {error}=await query;if(error)return alert(error.message);cancelEditOperation();loadAll()})
userForm.addEventListener('submit',async e=>{e.preventDefault();const r=userRole.value,leader_operation_ids=[...leaderOperation.selectedOptions].map(x=>x.value),onsite_operation_ids=[...onsiteOperations.selectedOptions].map(x=>x.value);if(r==='leader'&&!leader_operation_ids.length)return alert('Selecione ao menos uma operação para o líder.');if(r==='onsite'&&!onsite_operation_ids.length)return alert('Selecione uma operação.');createUserBtn.disabled=true;const {data,error}=await db.functions.invoke('admin-create-user',{body:{full_name:userName.value.trim(),email:userEmail.value.trim(),phone:userPhone.value.trim(),role:r,shift_id:r==='leader'?leaderShift.value:null,operation_ids:r==='leader'?leader_operation_ids:r==='onsite'?onsite_operation_ids:[]}});createUserBtn.disabled=false;if(error)return alert('Erro: '+await functionError(error));credentialEmail.textContent=data.email;credentialPassword.textContent=data.temporary_password;credentialsBox.classList.remove('hidden');e.target.reset();loadAll()})
editUserForm.addEventListener('submit',async e=>{e.preventDefault();const role=editUserRole.value,leader_operation_ids=[...editLeaderOperation.selectedOptions].map(x=>x.value),onsite_operation_ids=[...editOnsiteOperations.selectedOptions].map(x=>x.value);if(role==='leader'&&!leader_operation_ids.length)return alert('Selecione ao menos uma operação para o líder.');if(role==='onsite'&&!onsite_operation_ids.length)return alert('Selecione ao menos uma operação.');const data=await manageUser({action:'update-user',user_id:editUserId.value,full_name:editUserName.value.trim(),email:editUserEmail.value.trim().toLowerCase(),phone:editUserPhone.value.trim(),role,shift_id:role==='leader'?editLeaderShift.value:null,operation_ids:role==='leader'?leader_operation_ids:role==='onsite'?onsite_operation_ids:[]});if(data){alert('Usuário atualizado com sucesso!');closeEditUser();loadAll()}})
async function assignRequest(id){const onsite=document.getElementById(`assign-${id}`).value;if(!onsite)return alert('Selecione o Onsite.');const {error}=await db.from('disciplinary_requests').update({assigned_onsite_id:onsite,status:'atribuido'}).eq('id',id);if(error)return alert(error.message);loadAll()}
async function manageUser(body){const {data,error}=await db.functions.invoke('admin-manage-user',{body});if(error){alert('Erro: '+await functionError(error));return null}return data}
async function toggleUser(id,active){const {error}=await db.rpc('admin_set_user_active',{target_user_id:id,new_active:active});if(error)return alert('Erro ao alterar o usuário: '+error.message);await loadAll()}
async function resetPassword(id){if(!confirm('Gerar uma nova senha temporária?'))return;const data=await manageUser({action:'reset-password',user_id:id});if(data){credentialEmail.textContent=data.email;credentialPassword.textContent=data.temporary_password;credentialsBox.classList.remove('hidden');showPage('users',document.querySelectorAll('.nav-btn')[2])}}
getSessionContext('admin').then(x=>{if(x){ctx=x;loadAll()}})
