let ctx,clients=[],operations=[],shifts=[],profiles=[],links=[],requests=[]
const options=(items,label,fn)=>`<option value="">${label}</option>`+items.map(x=>`<option value="${x.id}">${escapeHTML(fn(x))}</option>`).join('')
async function loadAll(){
  const results=await Promise.all([
    db.from('clients').select('*').order('name'),db.from('operations').select('*,clients(name)').order('department'),db.from('shifts').select('*').order('name'),db.from('profiles').select('*,operations(cost_center,department),shifts(name)').order('full_name'),db.from('onsite_operations').select('*'),db.from('disciplinary_requests').select('*,operations(cost_center,department)').order('created_at',{ascending:false}),db.from('request_audit_log').select('*').order('created_at',{ascending:false}).limit(100)
  ])
  ;[clients,operations,shifts,profiles,links,requests]=results.slice(0,6).map(r=>r.data||[])
  renderSelects();renderUsers();renderOperations();renderRequests();renderAudit(results[6].data||[]);renderStats()
}
function renderStats(){statUsers.textContent=profiles.filter(x=>x.active).length;statPending.textContent=requests.filter(x=>!x.assigned_onsite_id).length;statOperations.textContent=operations.filter(x=>x.active).length}
function renderSelects(){operationClient.innerHTML=options(clients.filter(x=>x.active),'Selecione o cliente',x=>x.name);const ops=options(operations.filter(x=>x.active),'Selecione a operação',x=>`${x.clients?.name||''} | ${x.cost_center} | ${x.department}`);leaderOperation.innerHTML=ops;onsiteOperations.innerHTML=ops.replace('<option value="">Selecione a operação</option>','');leaderShift.innerHTML=options(shifts.filter(x=>x.active),'Selecione o turno',x=>x.name)}
function renderUsers(){const q=userSearch.value.toLowerCase(),role=userRoleFilter.value;const rows=profiles.filter(p=>(!role||p.role===role)&&(`${p.full_name} ${p.email}`.toLowerCase().includes(q))).map(p=>{const detail=p.role==='leader'?`${p.operations?.cost_center||'—'} / ${p.shifts?.name||'—'}`:p.role==='onsite'?`${links.filter(x=>x.onsite_id===p.id).length} operação(ões)`:'—';return `<tr><td><strong>${escapeHTML(p.full_name)}</strong></td><td>${roleLabel(p.role)}</td><td>${escapeHTML(p.email)}</td><td>${escapeHTML(detail)}</td><td><span class="badge ${p.active?'badge-green':'badge-gray'}">${p.active?'Ativo':'Inativo'}</span></td><td><div class="actions"><button class="btn btn-light" onclick="toggleUser('${p.id}',${!p.active})">${p.active?'Desativar':'Reativar'}</button><button class="btn btn-light" onclick="resetPassword('${p.id}')">Nova senha</button></div></td></tr>`}).join('');userRows.innerHTML=rows||'<tr><td colspan="6" class="empty">Nenhum usuário encontrado.</td></tr>'}
function renderOperations(){operationRows.innerHTML=operations.map(o=>`<tr><td>${escapeHTML(o.clients?.name)}</td><td>${escapeHTML(o.cost_center)}</td><td>${escapeHTML(o.department)}</td><td><span class="badge ${o.active?'badge-green':'badge-gray'}">${o.active?'Ativa':'Inativa'}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhuma operação cadastrada.</td></tr>'}
function renderRequests(){assignmentRows.innerHTML=requests.map(r=>{const eligibleIds=links.filter(x=>x.operation_id===r.operation_id).map(x=>x.onsite_id),eligible=profiles.filter(p=>p.role==='onsite'&&p.active&&eligibleIds.includes(p.id)),select=r.assigned_onsite_id?escapeHTML(profiles.find(p=>p.id===r.assigned_onsite_id)?.full_name||'Onsite'):`<select id="assign-${r.id}" class="input"><option value="">Selecione...</option>${eligible.map(p=>`<option value="${p.id}">${escapeHTML(p.full_name)}</option>`).join('')}</select>`;return `<tr><td>${escapeHTML(r.employee_name)}</td><td>${escapeHTML(r.operations?.cost_center)}<br><small>${escapeHTML(r.operations?.department)}</small></td><td>${escapeHTML(r.penalty_type)}</td><td><span class="badge ${r.assigned_onsite_id?'badge-blue':'badge-yellow'}">${escapeHTML(r.status)}</span></td><td>${select}</td><td>${r.assigned_onsite_id?'—':`<button class="btn btn-primary" onclick="assignRequest('${r.id}')">Atribuir</button>`}</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Nenhuma solicitação.</td></tr>'}
function renderAudit(items){auditRows.innerHTML=items.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('pt-BR')}</td><td>${escapeHTML(profiles.find(p=>p.id===a.actor_id)?.full_name||'Sistema')}</td><td>${escapeHTML(a.action)}</td><td>${escapeHTML(a.old_status||'—')}</td><td>${escapeHTML(a.new_status||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum registro.</td></tr>'}
userRole.addEventListener('change',()=>{const r=userRole.value;leaderOperationField.classList.toggle('hidden',r!=='leader');leaderShiftField.classList.toggle('hidden',r!=='leader');onsiteOperationsField.classList.toggle('hidden',r!=='onsite');leaderOperation.required=r==='leader';leaderShift.required=r==='leader';onsiteOperations.required=r==='onsite'})
userSearch.addEventListener('input',renderUsers);userRoleFilter.addEventListener('change',renderUsers)
clientForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('clients').insert({name:clientName.value.trim()});if(error)return alert(error.message);e.target.reset();loadAll()})
shiftForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('shifts').insert({name:shiftName.value.trim()});if(error)return alert(error.message);e.target.reset();loadAll()})
operationForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('operations').insert({client_id:operationClient.value,cost_center:costCenter.value.trim().toUpperCase(),department:department.value.trim()});if(error)return alert(error.message);e.target.reset();loadAll()})
userForm.addEventListener('submit',async e=>{e.preventDefault();const r=userRole.value,operation_ids=[...onsiteOperations.selectedOptions].map(x=>x.value);if(r==='onsite'&&!operation_ids.length)return alert('Selecione uma operação.');createUserBtn.disabled=true;const {data,error}=await db.functions.invoke('admin-create-user',{body:{full_name:userName.value.trim(),email:userEmail.value.trim(),phone:userPhone.value.trim(),role:r,operation_id:r==='leader'?leaderOperation.value:null,shift_id:r==='leader'?leaderShift.value:null,operation_ids:r==='onsite'?operation_ids:[]}});createUserBtn.disabled=false;if(error)return alert('Erro: '+await functionError(error));credentialEmail.textContent=data.email;credentialPassword.textContent=data.temporary_password;credentialsBox.classList.remove('hidden');e.target.reset();loadAll()})
async function assignRequest(id){const onsite=document.getElementById(`assign-${id}`).value;if(!onsite)return alert('Selecione o Onsite.');const {error}=await db.from('disciplinary_requests').update({assigned_onsite_id:onsite,status:'atribuido'}).eq('id',id);if(error)return alert(error.message);loadAll()}
async function manageUser(body){const {data,error}=await db.functions.invoke('admin-manage-user',{body});if(error){alert('Erro: '+await functionError(error));return null}return data}
async function toggleUser(id,active){if(await manageUser({action:'set-active',user_id:id,active}))loadAll()}
async function resetPassword(id){if(!confirm('Gerar uma nova senha temporária?'))return;const data=await manageUser({action:'reset-password',user_id:id});if(data){credentialEmail.textContent=data.email;credentialPassword.textContent=data.temporary_password;credentialsBox.classList.remove('hidden');showPage('users',document.querySelectorAll('.nav-btn')[2])}}
getSessionContext('admin').then(x=>{if(x){ctx=x;loadAll()}})
