let ctx,reasons=[],selectedIncidentDates=[],leaderOperations=[],leaderEmployees=[]
function toggleSuspensionFields(){const isSuspension=penaltyType.value==='Suspensão';suspensionField.classList.toggle('hidden',!isSuspension);suspensionStartDate.required=isSuspension;suspensionReturnDate.required=isSuspension;if(isSuspension)setSuggestedSuspensionDate()}
function setSuggestedSuspensionDate(){if(!issueDate.value||suspensionStartDate.value)return;const date=new Date(`${issueDate.value}T12:00:00`);date.setDate(date.getDate()+1);suspensionStartDate.value=date.toISOString().slice(0,10);updateSuspensionReturnDate()}
function updateSuspensionReturnDate(){if(!suspensionStartDate.value)return;const date=new Date(`${suspensionStartDate.value}T12:00:00`);date.setDate(date.getDate()+Number(suspensionDays.value||1));suspensionReturnDate.value=date.toISOString().slice(0,10)}
penaltyType.addEventListener('change',toggleSuspensionFields)
issueDate.addEventListener('change',()=>{if(penaltyType.value==='Suspensão'){suspensionStartDate.value='';setSuggestedSuspensionDate()}})
suspensionStartDate.addEventListener('change',updateSuspensionReturnDate)
suspensionDays.addEventListener('change',updateSuspensionReturnDate)
function renderIncidentDates(){incidentDatesList.innerHTML=selectedIncidentDates.length?selectedIncidentDates.sort().map(d=>`<span class="badge badge-blue" style="display:inline-flex;align-items:center;gap:6px">${new Date(`${d}T00:00:00`).toLocaleDateString('pt-BR')} <button type="button" onclick="removeIncidentDate('${d}')" aria-label="Remover data" style="border:0;background:transparent;cursor:pointer;font-weight:bold">&times;</button></span>`).join(' '):'<span class="muted">Nenhuma data adicionada.</span>'}
function addIncidentDate(){const date=incidentDate.value;if(!date)return alert('Selecione uma data da ocorrência.');if(!selectedIncidentDates.includes(date))selectedIncidentDates.push(date);incidentDate.value='';renderIncidentDates()}
function removeIncidentDate(date){selectedIncidentDates=selectedIncidentDates.filter(d=>d!==date);renderIncidentDates()}
async function load(){const linked=await db.from('leader_operations').select('operation_id,operations(*,clients(name))').eq('leader_id',ctx.user.id);if(linked.error)return alert('Erro ao carregar operações: '+linked.error.message);leaderOperations=(linked.data||[]).map(link=>link.operations).filter(Boolean);requestOperation.innerHTML='<option value="">Selecione a operação...</option>'+leaderOperations.map(operation=>`<option value="${operation.id}">${escapeHTML(operation.cost_center)} — ${escapeHTML(operation.department)}</option>`).join('');leaderContext.textContent=leaderOperations.length===1?`${leaderOperations[0].clients?.name||''} • ${leaderOperations[0].cost_center} • ${leaderOperations[0].department}`:`${leaderOperations.length} operações disponíveis`;const employees=await db.from('employees').select('id,registration,full_name,operation_id,status').eq('status','ativo').order('full_name');if(employees.error)return alert('Erro ao carregar colaboradores: '+employees.error.message);leaderEmployees=employees.data||[];renderEmployeeOptions();requestOperation.addEventListener('change',renderEmployeeOptions);const rr=await db.from('penalty_reasons').select('*').order('code');reasons=rr.data||[];reasonId.innerHTML='<option value="">Selecione...</option>'+reasons.map(r=>`<option value="${r.id}">${escapeHTML(r.code)} — ${escapeHTML(r.title)}</option>`).join('');loadRequests()}
function renderEmployeeOptions(){employeeSelect.innerHTML='<option value="">Selecione o colaborador...</option>'+leaderEmployees.filter(e=>!requestOperation.value||e.operation_id===requestOperation.value).map(e=>`<option value="${e.id}">${escapeHTML(e.registration)} — ${escapeHTML(e.full_name)}</option>`).join('')}
async function loadRequests(){const {data}=await db.from('disciplinary_requests').select('*').eq('leader_id',ctx.user.id).order('created_at',{ascending:false});leaderRequestRows.innerHTML=(data||[]).map(r=>`<tr><td>${escapeHTML(r.employee_name)}</td><td>${escapeHTML(r.penalty_type)}</td><td>${escapeHTML(r.incident_date)}</td><td><span class="badge ${r.status==='aplicado'?'badge-green':r.assigned_onsite_id?'badge-blue':'badge-yellow'}">${escapeHTML(r.status)}</span></td><td>${new Date(r.created_at).toLocaleDateString('pt-BR')}</td><td>${r.applied_date?new Date(`${r.applied_date}T00:00:00`).toLocaleDateString('pt-BR'):r.status==='gerado'?`<button class="btn btn-success" onclick="confirmApplication('${r.id}')">Confirmar aplicação</button>`:'Aguardando documento'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma solicitação.</td></tr>'}
async function confirmApplication(id){const date=prompt('Data da aplicação (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;const {error}=await db.rpc('confirm_disciplinary_application',{target_request_id:id,target_date:date});if(error)return alert(error.message);alert('Aplicação confirmada.');loadRequests()}
requestForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedIncidentDates.length)return alert('Adicione pelo menos uma data da ocorrência.');const operation=leaderOperations.find(item=>item.id===requestOperation.value),employee=leaderEmployees.find(item=>item.id===employeeSelect.value);if(!operation||!employee)return alert('Selecione a operação e o colaborador.');const isSuspension=penaltyType.value==='Suspensão';if(isSuspension&&(!suspensionStartDate.value||!suspensionReturnDate.value))return alert('Preencha o início e o retorno da suspensão.');if(isSuspension&&suspensionReturnDate.value<=suspensionStartDate.value)return alert('A data de retorno deve ser posterior ao início da suspensão.');const payload={leader_id:ctx.user.id,employee_id:employee.id,employee_name:employee.full_name,location:operation.city_state||operation.department,penalty_type:penaltyType.value,reason_id:reasonId.value,incident_date:[...selectedIncidentDates].sort().map(formatDate).join(', '),issue_date:issueDate.value,suspension_days:isSuspension?Number(suspensionDays.value):null,suspension_start_date:isSuspension?suspensionStartDate.value:null,suspension_return_date:isSuspension?suspensionReturnDate.value:null,operation_id:operation.id,status:'aguardando_atribuicao'};const {data,error}=await db.from('disciplinary_requests').insert(payload).select('id').single();if(error)return alert(error.message);const occurrences=selectedIncidentDates.map(occurrence_date=>({request_id:data.id,occurrence_date}));const occurrenceSave=await db.from('request_occurrences').insert(occurrences);if(occurrenceSave.error)return alert(occurrenceSave.error.message);alert('Solicitação enviada ao Onsite responsável.');e.target.reset();selectedIncidentDates=[];renderIncidentDates();toggleSuspensionFields();requestCard.classList.add('hidden');loadRequests()})
getSessionContext('leader').then(x=>{if(x){ctx=x;load()}})
