let ctx,reasons=[],selectedIncidentDates=[]
penaltyType.addEventListener('change',()=>suspensionField.classList.toggle('hidden',penaltyType.value!=='Suspensão'))
function renderIncidentDates(){incidentDatesList.innerHTML=selectedIncidentDates.length?selectedIncidentDates.sort().map(d=>`<span class="badge badge-blue" style="display:inline-flex;align-items:center;gap:6px">${new Date(`${d}T00:00:00`).toLocaleDateString('pt-BR')} <button type="button" onclick="removeIncidentDate('${d}')" aria-label="Remover data" style="border:0;background:transparent;cursor:pointer;font-weight:bold">&times;</button></span>`).join(' '):'<span class="muted">Nenhuma data adicionada.</span>'}
function addIncidentDate(){const date=incidentDate.value;if(!date)return alert('Selecione uma data da ocorrência.');if(!selectedIncidentDates.includes(date))selectedIncidentDates.push(date);incidentDate.value='';renderIncidentDates()}
function removeIncidentDate(date){selectedIncidentDates=selectedIncidentDates.filter(d=>d!==date);renderIncidentDates()}
async function load(){const op=await db.from('operations').select('*,clients(name)').eq('id',ctx.profile.operation_id).single();if(op.data){requestLocation.value=op.data.city_state||op.data.department;leaderContext.textContent=`${op.data.clients?.name||''} • ${op.data.cost_center} • ${op.data.department}`}const rr=await db.from('penalty_reasons').select('*').order('code');reasons=rr.data||[];reasonId.innerHTML='<option value="">Selecione...</option>'+reasons.map(r=>`<option value="${r.id}">${escapeHTML(r.code)} — ${escapeHTML(r.title)}</option>`).join('');loadRequests()}
async function loadRequests(){const {data}=await db.from('disciplinary_requests').select('*').eq('leader_id',ctx.user.id).order('created_at',{ascending:false});leaderRequestRows.innerHTML=(data||[]).map(r=>`<tr><td>${escapeHTML(r.employee_name)}</td><td>${escapeHTML(r.penalty_type)}</td><td>${escapeHTML(r.incident_date)}</td><td><span class="badge ${r.status==='gerado'?'badge-green':r.assigned_onsite_id?'badge-blue':'badge-yellow'}">${escapeHTML(r.status)}</span></td><td>${new Date(r.created_at).toLocaleDateString('pt-BR')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma solicitação.</td></tr>'}
requestForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedIncidentDates.length)return alert('Adicione pelo menos uma data da ocorrência.');const savedLocation=requestLocation.value;const payload={leader_id:ctx.user.id,employee_name:employeeName.value.trim(),location:savedLocation,penalty_type:penaltyType.value,reason_id:reasonId.value,incident_date:[...selectedIncidentDates].sort().map(formatDate).join(', '),issue_date:issueDate.value,suspension_days:penaltyType.value==='Suspensão'?Number(suspensionDays.value):null,operation_id:ctx.profile.operation_id,status:'aguardando_atribuicao'};const {error}=await db.from('disciplinary_requests').insert(payload);if(error)return alert(error.message);alert('Solicitação enviada ao Administrador.');e.target.reset();selectedIncidentDates=[];renderIncidentDates();requestLocation.value=savedLocation;requestCard.classList.add('hidden');loadRequests()})
getSessionContext('leader').then(x=>{if(x){ctx=x;load()}})
