(() => {
 const root=document.getElementById('learningRoot');if(!root)return
 const state={ctx:null,levels:[],path:[],roster:[],operation:'',search:''}
 const esc=v=>escapeHTML(v??'')
 const statusLabel=v=>({not_started:'Não iniciada',in_progress:'Em andamento',completed:'Concluída',paused:'Pausada'}[v]||v)
 const isRH=()=>['admin','onsite'].includes(state.ctx?.profile?.role)
 function competencies(level){const x=level.competencies;return Array.isArray(x)?x:[]}
 function levelCard(l,assignment){const progress=Number(assignment?.progress_pct||0);return `<article class="level-card"><span class="level-number">${esc(l.code)}</span><h3>${esc(l.name)}</h3><p class="muted"><strong>Público:</strong> ${esc(l.target_audience)}</p><ul>${competencies(l).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="muted"><strong>Prática:</strong> ${esc(l.practical_application)}</p><p class="muted"><strong>Conclusão:</strong> ${esc(l.completion_criteria)}</p>${assignment?`<div class="progress"><span style="width:${Math.min(100,progress)}%"></span></div><p><strong>${progress}%</strong> · ${esc(statusLabel(assignment.status))}</p>`:'<span class="badge badge-gray">Ainda não atribuída</span>'}</article>`}
 function renderEmployee(){root.innerHTML=`<section class="retention-card"><div class="page-head compact"><div><h2>Minha jornada</h2><p class="muted">Os níveis são progressivos: primeiro domínio da base operacional, depois análise e, por fim, inteligência e gestão.</p></div></div><div class="retention-grid">${state.levels.map(l=>levelCard(l,state.path.find(a=>a.level_id===l.id))).join('')}</div></section>`}
 function operations(){const m=new Map();state.roster.forEach(r=>m.set(r.operation_id,r.operation_name||'Operação'));return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1]))}
 function filtered(){const t=state.search.trim().toLowerCase();return state.roster.filter(r=>(!state.operation||r.operation_id===state.operation)&&(!t||`${r.full_name} ${r.registration}`.toLowerCase().includes(t)))}
 function renderRH(){const rows=filtered();root.innerHTML=`<section class="retention-card"><div class="page-head compact"><div><h2>Universidade Corporativa</h2><p class="muted">Acompanhe a evolução dos colaboradores nas trilhas e registre conclusão com base em prática aplicada.</p></div></div><div class="retention-grid">${state.levels.map(l=>levelCard(l,null)).join('')}</div></section><section class="retention-card"><div class="page-head compact"><div><h2>Colaboradores</h2><p class="muted">Atribua e acompanhe níveis sem precisar abrir cadastro por cadastro.</p></div></div><div class="retention-toolbar"><label class="field"><span>Operação</span><select id="learningOperation" class="input"><option value="">Todas</option>${operations().map(([id,n])=>`<option value="${id}" ${state.operation===id?'selected':''}>${esc(n)}</option>`).join('')}</select></label><label class="field grow"><span>Buscar</span><input id="learningSearch" class="input" value="${esc(state.search)}" placeholder="Nome ou matrícula..."></label></div><div class="table-wrap"><table class="table"><thead><tr><th>Colaborador</th><th>Operação</th><th>Trilha atual</th><th>Progresso</th><th>Ação</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.full_name)}</strong><br><small>${esc(r.registration)}</small></td><td>${esc(r.operation_name||'—')}</td><td>${esc(r.level_code||'—')} ${esc(r.level_name||'')}</td><td>${r.progress_pct??0}% · ${esc(statusLabel(r.learning_status||'not_started'))}</td><td><button class="btn btn-light btn-small" data-manage="${r.employee_id}">Gerenciar</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum colaborador encontrado.</td></tr>'}</tbody></table></div></section><section id="learningEditor"></section>`;learningOperation.onchange=()=>{state.operation=learningOperation.value;renderRH()};learningSearch.oninput=()=>{state.search=learningSearch.value;renderRH()};document.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>openEditor(state.roster.find(r=>r.employee_id===b.dataset.manage)))}
 function openEditor(row){const currentLevel=state.levels.find(l=>l.id===row.level_id);learningEditor.innerHTML=`<section class="retention-card"><div class="page-head compact"><div><h2>${esc(row.full_name)}</h2><p class="muted">${esc(row.registration)} · ${esc(row.operation_name||'')}</p></div><button id="closeLearningEditor" class="btn btn-light btn-small">Fechar</button></div><form id="learningForm" class="retention-form-grid"><label class="field"><span>Nível</span><select id="learningLevel" class="input" required><option value="">Selecione...</option>${state.levels.map(l=>`<option value="${l.id}" ${row.level_id===l.id?'selected':''}>${esc(l.code)} · ${esc(l.name)}</option>`).join('')}</select></label><label class="field"><span>Status</span><select id="learningStatus" class="input"><option value="not_started">Não iniciada</option><option value="in_progress">Em andamento</option><option value="completed">Concluída</option><option value="paused">Pausada</option></select></label><label class="field"><span>Progresso (%)</span><input id="learningProgress" class="input" type="number" min="0" max="100" value="${row.progress_pct??0}"></label><label class="field"><span>Data de conclusão</span><input id="learningCompleted" class="input" type="date" value="${row.completed_at?String(row.completed_at).slice(0,10):''}"></label><label class="field full"><span>Observação / evidência da prática</span><textarea id="learningNotes" class="input" maxlength="1600">${esc(row.learning_notes||'')}</textarea></label><div class="full retention-actions"><span class="muted">Conclusão deve refletir a entrega prática definida no nível.</span><button class="btn btn-primary" type="submit">Salvar trilha</button></div></form></section>`;learningStatus.value=row.learning_status||'not_started';closeLearningEditor.onclick=()=>learningEditor.innerHTML='';learningForm.onsubmit=e=>save(e,row)}
 async function save(e,row){e.preventDefault();const btn=e.submitter;btn.disabled=true;const {error}=await db.rpc('save_learning_assignment',{p_employee_id:row.employee_id,p_level_id:learningLevel.value,p_status:learningStatus.value,p_progress_pct:Number(learningProgress.value||0),p_notes:learningNotes.value.trim()||null,p_completed_at:learningCompleted.value||null});btn.disabled=false;if(error)return alert(error.message);alert('Trilha atualizada.');await load()}
 async function load(){const c=await db.rpc('get_learning_catalog');if(c.error)return alert(c.error.message);state.levels=c.data||[];if(isRH()){const r=await db.rpc('get_learning_roster');if(r.error)return alert(r.error.message);state.roster=r.data||[];renderRH()}else{const r=await db.rpc('get_my_learning_path');if(r.error)return alert(r.error.message);state.path=r.data||[];renderEmployee()}}
 getSessionContext().then(async ctx=>{if(!ctx)return;state.ctx=ctx;if(!requireModuleAccess(ctx.profile,'learning'))return;renderPortalSidebar(portalSidebar,ctx.profile,'learning');await load()})
})()
