let managementEmployees=[],managementScales=[],managementBenefits=[],managementPrivate=[],managementEmployeeBenefits=[],managementMeasures=[]

async function loadManagement(){const result=await Promise.all([db.from('employees').select('*,operations(cost_center,department,clients(name))').order('full_name'),db.from('work_scales').select('*').order('name'),db.from('benefits').select('*').order('name'),db.from('employee_private_data').select('*'),db.from('employee_benefits').select('*'),db.from('disciplinary_requests').select('employee_id,penalty_type')]);if(result.some(x=>x.error))return alert(result.find(x=>x.error).error.message);[managementEmployees,managementScales,managementBenefits,managementPrivate,managementEmployeeBenefits,managementMeasures]=result.map(x=>x.data||[]);renderManagementSelects();renderEmployees()}

function renderManagementSelects(){employeeOperation.innerHTML='<option value="">Selecione...</option>'+operations.map(o=>`<option value="${o.id}">${escapeHTML(o.clients?.name||'')} | ${escapeHTML(o.cost_center)} | ${escapeHTML(o.department)}</option>`).join('');employeeLeader.innerHTML='<option value="">Selecione...</option>'+profiles.filter(p=>p.role==='leader'&&p.active).map(p=>`<option value="${p.id}">${escapeHTML(p.full_name)}</option>`).join('');employeeShift.innerHTML='<option value="">Selecione...</option>'+shifts.filter(s=>s.active).map(s=>`<option value="${s.id}">${escapeHTML(s.name)}</option>`).join('');employeeScale.innerHTML='<option value="">Selecione...</option>'+managementScales.filter(s=>s.active).map(s=>`<option value="${s.id}">${escapeHTML(s.name)}</option>`).join('');employeeBenefits.innerHTML=managementBenefits.filter(b=>b.active).map(b=>`<option value="${b.id}">${escapeHTML(b.name)}</option>`).join('')}

function renderEmployees(){const q=employeeSearch.value.trim().toLowerCase();employeeRows.innerHTML=managementEmployees.filter(e=>`${e.registration} ${e.full_name}`.toLowerCase().includes(q)).map(e=>{const measures=managementMeasures.filter(m=>m.employee_id===e.id),warnings=measures.filter(m=>m.penalty_type.toLowerCase().includes('advert')).length,suspensions=measures.filter(m=>m.penalty_type.toLowerCase().includes('susp')).length;return `<tr><td>${escapeHTML(e.registration)}</td><td><strong>${escapeHTML(e.full_name)}</strong></td><td>${escapeHTML(e.operations?.cost_center||'—')}<br><small>${escapeHTML(e.operations?.department||'')}</small></td><td><span class="badge ${e.status==='ativo'?'badge-green':'badge-gray'}">${escapeHTML(e.status)}</span></td><td>${warnings}</td><td>${suspensions}</td><td><button class="btn btn-light" onclick="editEmployee('${e.id}')">Editar</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Nenhum colaborador cadastrado.</td></tr>'}

function openEmployeeForm(){employeeForm.reset();employeeId.value='';employeeFormTitle.textContent='Cadastrar colaborador';employeeFormCard.classList.remove('hidden');employeeFormCard.scrollIntoView({behavior:'smooth'})}
function closeEmployeeForm(){employeeFormCard.classList.add('hidden');employeeForm.reset()}
function editEmployee(id){const e=managementEmployees.find(x=>x.id===id),privateData=managementPrivate.find(x=>x.employee_id===id);if(!e)return;openEmployeeForm();employeeFormTitle.textContent='Editar colaborador';employeeId.value=e.id;employeeRegistration.value=e.registration;managementEmployeeName.value=e.full_name;managementEmployeeCpf.value=privateData?.cpf||'';employeeSex.value=e.sex||'Não informado';employeeBirthDate.value=privateData?.birth_date||'';employeeAdmissionDate.value=e.admission_date||'';employeeDismissalDate.value=e.dismissal_date||'';employeeOperation.value=e.operation_id||'';employeeLeader.value=e.leader_id||'';employeeShift.value=e.shift_id||'';employeeScale.value=e.scale_id||'';employeeContractEnd.value=e.contract_end_date||'';employeeContractExtension.value=e.contract_extension_date||'';employeePhone.value=e.phone||'';employeeEmail.value=e.email||'';employeeStatus.value=e.status;employeeVest.value=e.vest_size||'';employeeGlove.value=e.glove_size||'';employeeBoot.value=e.boot_size||'';const selected=managementEmployeeBenefits.filter(x=>x.employee_id===id).map(x=>x.benefit_id);[...employeeBenefits.options].forEach(o=>o.selected=selected.includes(o.value))}

managementEmployeeCpf.addEventListener('input',()=>{const d=managementEmployeeCpf.value.replace(/\D/g,'').slice(0,11);managementEmployeeCpf.value=d.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')})
employeeSearch.addEventListener('input',renderEmployees)
scaleForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('work_scales').insert({name:scaleName.value.trim(),description:scaleDescription.value.trim()||null});if(error)return alert(error.message);e.target.reset();loadManagement()})
benefitForm.addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.from('benefits').insert({name:benefitName.value.trim()});if(error)return alert(error.message);e.target.reset();loadManagement()})
employeeForm.addEventListener('submit',async e=>{e.preventDefault();if(managementEmployeeCpf.value.replace(/\D/g,'').length!==11)return alert('Informe um CPF com 11 números.');const payload={registration:employeeRegistration.value.trim(),full_name:managementEmployeeName.value.trim(),operation_id:employeeOperation.value,leader_id:employeeLeader.value||null,shift_id:employeeShift.value||null,scale_id:employeeScale.value||null,sex:employeeSex.value,admission_date:employeeAdmissionDate.value,dismissal_date:employeeDismissalDate.value||null,contract_end_date:employeeContractEnd.value||null,contract_extension_date:employeeContractExtension.value||null,phone:employeePhone.value.trim()||null,email:employeeEmail.value.trim()||null,status:employeeStatus.value,vest_size:employeeVest.value.trim()||null,glove_size:employeeGlove.value.trim()||null,boot_size:employeeBoot.value.trim()||null,updated_at:new Date().toISOString()};let id=employeeId.value;if(id){const {error}=await db.from('employees').update(payload).eq('id',id);if(error)return alert(error.message)}else{const {data,error}=await db.from('employees').insert(payload).select('id').single();if(error)return alert(error.message);id=data.id}const privateSave=await db.from('employee_private_data').upsert({employee_id:id,cpf:managementEmployeeCpf.value,birth_date:employeeBirthDate.value});if(privateSave.error)return alert(privateSave.error.message);await db.from('employee_benefits').delete().eq('employee_id',id);const selected=[...employeeBenefits.selectedOptions].map(x=>({employee_id:id,benefit_id:x.value}));if(selected.length){const linked=await db.from('employee_benefits').insert(selected);if(linked.error)return alert(linked.error.message)}alert('Colaborador salvo com sucesso!');closeEmployeeForm();loadManagement()})
