let ctx,signature=''

signatureInput.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async ev=>{signature=ev.target.result;signaturePreview.src=signature;signaturePreview.classList.remove('hidden');const {error}=await db.from('profiles').update({signature_url:signature}).eq('id',ctx.user.id);if(error)alert(error.message)};reader.readAsDataURL(file)})

async function loadRequests(){const {data,error}=await db.from('disciplinary_requests').select('*,penalty_reasons(*),operations(cost_center,department)').eq('assigned_onsite_id',ctx.user.id).order('created_at',{ascending:false});if(error)return alert(error.message);onsiteRequestRows.innerHTML=(data||[]).map(r=>`<tr><td>${escapeHTML(r.employee_name)}</td><td>${escapeHTML(r.operations?.cost_center)}<br><small>${escapeHTML(r.operations?.department)}</small></td><td>${escapeHTML(r.penalty_type)}${r.suspension_days?` (${r.suspension_days} dia(s))`:''}</td><td>${escapeHTML(r.penalty_reasons?.title)}</td><td><span class="badge ${r.status==='aplicado'?'badge-green':'badge-blue'}">${escapeHTML(r.status)}</span></td><td>${['gerado','aplicado'].includes(r.status)?'Documento baixado':`<button class="btn btn-success" onclick="prepareDocument('${r.id}')">Gerar PDF</button>`}</td><td>${r.applied_date?new Date(`${r.applied_date}T00:00:00`).toLocaleDateString('pt-BR'):r.status==='gerado'?`<button class="btn btn-primary" onclick="confirmOnsiteApplication('${r.id}')">Confirmar</button>`:'Aguardando documento'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nenhuma solicitação atribuída.</td></tr>'}

async function confirmOnsiteApplication(id){const date=prompt('Data da aplicação (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;const {error}=await db.rpc('confirm_disciplinary_application',{target_request_id:id,target_date:date});if(error)return alert(error.message);alert('Aplicação confirmada.');loadRequests()}

async function fetchRequest(id){const {data,error}=await db.from('disciplinary_requests').select('*,penalty_reasons(*),operations(city_state)').eq('id',id).single();if(error){alert(error.message);return null}return data}

async function prepareDocument(id){if(!signature)return alert('Cadastre sua assinatura antes de gerar o documento.');const request=await fetchRequest(id);if(!request)return;if(request.penalty_type.toLowerCase().includes('susp')){if(!request.employee_id)return alert('Esta solicitação não está associada a um colaborador cadastrado.');const {data:privateData,error}=await db.from('employee_private_data').select('cpf').eq('employee_id',request.employee_id).single();if(error||!privateData?.cpf)return alert('CPF não encontrado. Peça ao Admin para revisar o cadastro do colaborador.');request.employee_cpf=privateData.cpf}await generateAndFinish(request)}

async function generateAndFinish(request){await generateDisciplinaryPDF(request,signature);const {error}=await db.from('disciplinary_requests').update({status:'gerado'}).eq('id',request.id);if(error)return alert(error.message);loadRequests()}

getSessionContext('onsite').then(x=>{if(x){ctx=x;signature=x.profile.signature_url||'';if(signature){signaturePreview.src=signature;signaturePreview.classList.remove('hidden')}loadRequests()}})
