let presenceCtx,presenceOperations=[],presenceEmployees=[],presenceScales=[],presenceScaleDays=[],presenceScaleHistory=[],presenceRecords=[],presenceDirty=new Map(),pickerTarget=null
const attendanceTypes=[
 {code:'AF',label:'Afastamento (1º ao 15º dia)',group:'away'},
 {code:'AL',label:'Afastamento por INSS, licença-maternidade ou similar',group:'away'},
 {code:'AM',label:'Atestado médico',group:'am'},
 {code:'BH',label:'Banco de horas',group:'rest'},
 {code:'DF',label:'Desligamento forçado pelo gestor(a)',group:'move'},
 {code:'DP',label:'Desligamento planejado para readequação de quadro',group:'move'},
 {code:'DSR',label:'Descanso Semanal Remunerado',group:'rest'},
 {code:'DV',label:'Desligamento voluntário pelo colaborador',group:'move'},
 {code:'F',label:'Falta injustificada',group:'f'},
 {code:'FE',label:'Período de férias do colaborador',group:'rest'},
 {code:'FJ',label:'Falta justificada por motivos previstos na CLT',group:'am'},
 {code:'FO',label:'Folga acordada entre colaborador e Site Leader',group:'rest'},
 {code:'FR',label:'Período de férias do colaborador',group:'rest'},
 {code:'NC',label:'Colaborador ingressante no mês',group:'move'},
 {code:'NS',label:'No-show (ausência sem justificativa)',group:'f'},
 {code:'P',label:'Presença do colaborador nas atividades',group:'p'},
 {code:'PR',label:'Promoção para Analista',group:'move'},
 {code:'S1',label:'Sinergia enviada para outra operação',group:'move'},
 {code:'S2',label:'Sinergia recebida de outra operação',group:'move'},
 {code:'TD',label:'Treinamento e desenvolvimento',group:'move'},
 {code:'TR',label:'Transferência fixa para outra operação',group:'move'}
]
const legacyStatus={presente:'P',injustificada:'F',justificada:'AM'},weekdayShort=['D','S','T','Q','Q','S','S']
function typeInfo(code){return attendanceTypes.find(x=>x.code===code)}
function statusClass(code){const group=typeInfo(code)?.group;return group==='p'?'status-p':group==='f'?'status-f':group==='am'?'status-am':group==='away'?'status-away':group==='rest'?'status-rest':group==='move'?'status-move':''}
function presenceRange(){const value=presenceMonth.value||new Date().toISOString().slice(0,7),[year,month]=value.split('-').map(Number),last=new Date(year,month,0).getDate();return {value,year,month,last,start:`${value}-01`,end:`${value}-${String(last).padStart(2,'0')}`}}
function isoDay(year,month,day){return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function employeeScaleAt(employeeId,date){return presenceScaleHistory.filter(x=>x.employee_id===employeeId&&x.effective_from<=date&&(!x.effective_to||x.effective_to>=date)).sort((a,b)=>b.effective_from.localeCompare(a.effective_from))[0]?.scale_id||presenceEmployees.find(x=>x.id===employeeId)?.scale_id||null}
function isWorkday(employee,date){if(date<employee.admission_date||employee.dismissal_date&&date>employee.dismissal_date)return false;const scaleId=employeeScaleAt(employee.id,date),weekday=new Date(`${date}T12:00:00`).getDay();return presenceScaleDays.some(x=>x.scale_id===scaleId&&x.weekday===weekday)}
function recordKey(employeeId,date){return `${employeeId}|${date}`}
function currentStatus(employeeId,date){const key=recordKey(employeeId,date);if(presenceDirty.has(key))return presenceDirty.get(key).status;const saved=presenceRecords.find(x=>x.employee_id===employeeId&&x.absence_date===date)?.absence_type||'';return legacyStatus[saved]||saved}
async function loadPresence(){const selectedOperation=presenceOperationFilter.value,selectedScale=presenceShiftFilter.value,{start,end}=presenceRange();const [links,employees,scales,scaleDays,history,records]=await Promise.all([db.from('leader_operations').select('operation_id,operations(id,cost_center,department)').eq('leader_id',presenceCtx.user.id),db.from('employees').select('id,registration,full_name,operation_id,scale_id,admission_date,dismissal_date,status').order('full_name'),db.from('work_scales').select('*').eq('active',true).order('name'),db.from('scale_work_days').select('*'),db.from('employee_scale_history').select('*').lte('effective_from',end).or(`effective_to.is.null,effective_to.gte.${start}`),db.from('attendance_absences').select('*').gte('absence_date',start).lte('absence_date',end)]);const failed=[links,employees,scales,scaleDays,history,records].find(x=>x.error);if(failed)return alert(failed.error.message);presenceOperations=(links.data||[]).map(x=>x.operations).filter(Boolean);presenceEmployees=(employees.data||[]).filter(e=>presenceOperations.some(o=>o.id===e.operation_id)&&e.admission_date<=end&&(!e.dismissal_date||e.dismissal_date>=start));presenceScales=scales.data||[];presenceScaleDays=scaleDays.data||[];presenceScaleHistory=history.data||[];presenceRecords=records.data||[];presenceDirty.clear();presenceOperationFilter.innerHTML='<option value="">Todas as operações</option>'+presenceOperations.map(o=>`<option value="${o.id}">${escapeHTML(o.cost_center)} — ${escapeHTML(o.department)}</option>`).join('');presenceShiftFilter.innerHTML='<option value="">Todos os turnos / escalas</option>'+presenceScales.map(s=>`<option value="${s.id}">${escapeHTML(s.description||s.name)}</option>`).join('');if(presenceOperations.some(x=>x.id===selectedOperation))presenceOperationFilter.value=selectedOperation;if(presenceScales.some(x=>x.id===selectedScale))presenceShiftFilter.value=selectedScale;renderAttendance();updateDirtyState()}
function filteredEmployees(){const q=presenceSearch.value.trim().toLowerCase(),operation=presenceOperationFilter.value,scale=presenceShiftFilter.value,{start,end}=presenceRange();return presenceEmployees.filter(e=>{const matchesScale=!scale||presenceScaleHistory.some(h=>h.employee_id===e.id&&h.scale_id===scale&&h.effective_from<=end&&(!h.effective_to||h.effective_to>=start))||e.scale_id===scale;return(!operation||e.operation_id===operation)&&(!q||`${e.registration} ${e.full_name}`.toLowerCase().includes(q))&&matchesScale})}
function renderAttendance(){const {year,month,last}=presenceRange(),employees=filteredEmployees();attendanceHead.innerHTML=`<tr><th class="sticky-col sticky-mat">MAT</th><th class="sticky-col sticky-name">Colaborador</th>${Array.from({length:last},(_,i)=>{const day=i+1,date=isoDay(year,month,day),weekday=new Date(`${date}T12:00:00`).getDay();return `<th class="day-head ${weekday===0||weekday===6?'weekend':''}">${String(day).padStart(2,'0')}<small>${weekdayShort[weekday]}</small></th>`}).join('')}</tr>`;attendanceRows.innerHTML=employees.map(employee=>`<tr><td class="sticky-col sticky-mat">${escapeHTML(employee.registration)}</td><td class="sticky-col sticky-name"><strong>${escapeHTML(employee.full_name)}</strong></td>${Array.from({length:last},(_,i)=>attendanceCell(employee,isoDay(year,month,i+1))).join('')}</tr>`).join('')||`<tr><td colspan="${last+2}" class="empty">Nenhum colaborador encontrado para os filtros.</td></tr>`}
function attendanceCell(employee,date){const inside=date>=employee.admission_date&&(!employee.dismissal_date||date<=employee.dismissal_date);if(!inside)return '<td class="attendance-cell status-na" title="Fora do vínculo">—</td>';const status=currentStatus(employee.id,date),planned=isWorkday(employee,date),code=status||(planned?'':'FO'),info=typeInfo(code),css=statusClass(code);return `<td class="attendance-cell ${css}" title="${escapeHTML(info?.label||'Sem marcação')}" data-employee="${employee.id}" data-date="${date}" data-planned="${planned}" onclick="openAttendancePicker(this)">${code}</td>`}
function renderAttendanceLegend(){attendanceLegend.innerHTML=attendanceTypes.map(x=>`<div class="legend-item"><span class="attendance-status ${statusClass(x.code)}">${x.code}</span><span>${escapeHTML(x.label)}</span></div>`).join('')}
function openAttendancePicker(cell){pickerTarget=cell;const employee=presenceEmployees.find(x=>x.id===cell.dataset.employee),date=new Date(`${cell.dataset.date}T00:00:00`);pickerEmployee.textContent=employee?.full_name||'';pickerDate.textContent=date.toLocaleDateString('pt-BR');attendanceOptions.innerHTML=`<button type="button" class="attendance-option" onclick="chooseAttendance('')"><span class="attendance-status">—</span><span><strong>Limpar marcação</strong><small>${cell.dataset.planned==='true'?'Deixar o dia sem informação':'Voltar para a folga FO da escala'}</small></span></button>`+attendanceTypes.map(x=>`<button type="button" class="attendance-option" onclick="chooseAttendance('${x.code}')"><span class="attendance-status ${statusClass(x.code)}">${x.code}</span><span><strong>${x.code}</strong><small>${escapeHTML(x.label)}</small></span></button>`).join('');attendancePicker.showModal()}
function closeAttendancePicker(){attendancePicker.close();pickerTarget=null}
function chooseAttendance(status){if(!pickerTarget)return;const employeeId=pickerTarget.dataset.employee,date=pickerTarget.dataset.date,employee=presenceEmployees.find(x=>x.id===employeeId);presenceDirty.set(recordKey(employeeId,date),{employee_id:employeeId,absence_date:date,status,operation_id:employee.operation_id});attendancePicker.close();pickerTarget=null;renderAttendance();updateDirtyState()}
function updateDirtyState(){saveAttendanceButton.disabled=!presenceDirty.size;saveAttendanceButton.textContent=presenceDirty.size?`Salvar ${presenceDirty.size} marcação(ões)`:'Salvar marcações'}
async function saveAttendance(){if(!presenceDirty.size)return;saveAttendanceButton.disabled=true;const changes=[...presenceDirty.values()],toDelete=changes.filter(x=>!x.status).map(x=>presenceRecords.find(r=>r.employee_id===x.employee_id&&r.absence_date===x.absence_date)?.id).filter(Boolean),toSave=changes.filter(x=>x.status).map(x=>({employee_id:x.employee_id,absence_date:x.absence_date,absence_type:x.status,notes:null,operation_id:x.operation_id,leader_id:presenceCtx.user.id}));if(toDelete.length){const removed=await db.from('attendance_absences').delete().in('id',toDelete);if(removed.error){saveAttendanceButton.disabled=false;return alert(removed.error.message)}}if(toSave.length){const saved=await db.from('attendance_absences').upsert(toSave,{onConflict:'employee_id,absence_date'});if(saved.error){saveAttendanceButton.disabled=false;return alert(saved.error.message)}}alert('Marcações salvas com sucesso.');loadPresence()}
presenceSearch.addEventListener('input',renderAttendance);presenceOperationFilter.addEventListener('change',renderAttendance);presenceShiftFilter.addEventListener('change',renderAttendance);presenceMonth.addEventListener('change',loadPresence);attendancePicker.addEventListener('click',e=>{if(e.target===attendancePicker)closeAttendancePicker()});renderAttendanceLegend()
getSessionContext('leader').then(x=>{if(x){presenceCtx=x;presenceMonth.value=new Date().toISOString().slice(0,7);loadPresence()}})
